//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordStore.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UILabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UILabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecordStore.Core.Resources.UILabels", typeof(UILabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add authenticator app.
        /// </summary>
        public static string AddAuthenticatorApp {
            get {
                return ResourceManager.GetString("AddAuthenticatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Record.
        /// </summary>
        public static string AddRecordHeader {
            get {
                return ResourceManager.GetString("AddRecordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new Record.
        /// </summary>
        public static string AddRecordTitle {
            get {
                return ResourceManager.GetString("AddRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new user.
        /// </summary>
        public static string AddUserHeader {
            get {
                return ResourceManager.GetString("AddUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new user.
        /// </summary>
        public static string AddUserTitle {
            get {
                return ResourceManager.GetString("AddUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string AdminHome {
            get {
                return ResourceManager.GetString("AdminHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page should only be visible to admin..
        /// </summary>
        public static string AdminIndexDescription {
            get {
                return ResourceManager.GetString("AdminIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Admin Page.
        /// </summary>
        public static string AdminIndexTitle {
            get {
                return ResourceManager.GetString("AdminIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Tools.
        /// </summary>
        public static string AdminTools {
            get {
                return ResourceManager.GetString("AdminTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authenticator app has been verified..
        /// </summary>
        public static string AuthAppVerified {
            get {
                return ResourceManager.GetString("AuthAppVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use an authenticator app go through the following steps:.
        /// </summary>
        public static string AuthConfigInstructions {
            get {
                return ResourceManager.GetString("AuthConfigInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator app.
        /// </summary>
        public static string AuthenticatorApp {
            get {
                return ResourceManager.GetString("AuthenticatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authenticator app key has been reset, you will need to configure your authenticator app using the new key..
        /// </summary>
        public static string AuthenticatorResetSuccessfully {
            get {
                return ResourceManager.GetString("AuthenticatorResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process disables 2FA until you verify your authenticator app. If you do not complete your authenticator app configuration you may lose access to your account..
        /// </summary>
        public static string AuthentificatorKeyResetDetails {
            get {
                return ResourceManager.GetString("AuthentificatorKeyResetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you reset your authenticator key your authenticator app will not work until you reconfigure it..
        /// </summary>
        public static string AuthentificatorKeyResetWarning {
            get {
                return ResourceManager.GetString("AuthentificatorKeyResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current browser has been forgotten. When you login again from this browser you will be prompted for your 2fa code..
        /// </summary>
        public static string BrowserForgotten {
            get {
                return ResourceManager.GetString("BrowserForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string ChangeAccountSettingsHeader {
            get {
                return ResourceManager.GetString("ChangeAccountSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email.
        /// </summary>
        public static string ChangeEmailAction {
            get {
                return ResourceManager.GetString("ChangeEmailAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure authenticator app.
        /// </summary>
        public static string ConfigureAuthenticatorTitle {
            get {
                return ResourceManager.GetString("ConfigureAuthenticatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateRecordAction {
            get {
                return ResourceManager.GetString("CreateRecordAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeletePersonalData {
            get {
                return ResourceManager.GetString("DeletePersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteRecordAction {
            get {
                return ResourceManager.GetString("DeleteRecordAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Record?.
        /// </summary>
        public static string DeleteRecordConfirmationHeader {
            get {
                return ResourceManager.GetString("DeleteRecordConfirmationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteRecordHeader {
            get {
                return ResourceManager.GetString("DeleteRecordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Record.
        /// </summary>
        public static string DeleteRecordTitle {
            get {
                return ResourceManager.GetString("DeleteRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string Disable2FA {
            get {
                return ResourceManager.GetString("Disable2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a two-factor authenticator app like Microsoft Authenticator for {0} and {1} or Google Authenticator for {2} and {3}..
        /// </summary>
        public static string DownloadAuthenticators {
            get {
                return ResourceManager.GetString("DownloadAuthenticators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadPersonalData {
            get {
                return ResourceManager.GetString("DownloadPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditRecord {
            get {
                return ResourceManager.GetString("EditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Record.
        /// </summary>
        public static string EditRecordHeader {
            get {
                return ResourceManager.GetString("EditRecordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditRecordTitle {
            get {
                return ResourceManager.GetString("EditRecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user details.
        /// </summary>
        public static string EditUserHeader {
            get {
                return ResourceManager.GetString("EditUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user details.
        /// </summary>
        public static string EditUserTitle {
            get {
                return ResourceManager.GetString("EditUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid..
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email is unchanged..
        /// </summary>
        public static string EmailUnchanged {
            get {
                return ResourceManager.GetString("EmailUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en_US {
            get {
                return ResourceManager.GetString("en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string EnterEmailHeader {
            get {
                return ResourceManager.GetString("EnterEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error when trying to set phone number..
        /// </summary>
        public static string ErrorSettingPhoneNumber {
            get {
                return ResourceManager.GetString("ErrorSettingPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External logins.
        /// </summary>
        public static string ExternalLogins {
            get {
                return ResourceManager.GetString("ExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to register..
        /// </summary>
        public static string ExternalRegister {
            get {
                return ResourceManager.GetString("ExternalRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget this browser.
        /// </summary>
        public static string ForgetThisBrowser {
            get {
                return ResourceManager.GetString("ForgetThisBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have scanned the QR code or input the key above, your two factor authentication app will provide you with a unique code. Enter the code in the confirmation box below..
        /// </summary>
        public static string InstructionsFor2FAConfirmationCode {
            get {
                return ResourceManager.GetString("InstructionsFor2FAConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is invalid..
        /// </summary>
        public static string InvalidVerificationCode {
            get {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invlid phone number..
        /// </summary>
        public static string InvlidPhoneNumber {
            get {
                return ResourceManager.GetString("InvlidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout.
        /// </summary>
        public static string Lockout {
            get {
                return ResourceManager.GetString("Lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to your account.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your {0} account.
        /// </summary>
        public static string LoginUsing {
            get {
                return ResourceManager.GetString("LoginUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Logout.
        /// </summary>
        public static string LogoutAction {
            get {
                return ResourceManager.GetString("LogoutAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged out of the application..
        /// </summary>
        public static string LogoutSuccessful {
            get {
                return ResourceManager.GetString("LogoutSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogoutTitle {
            get {
                return ResourceManager.GetString("LogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string ManageAccountHeader {
            get {
                return ResourceManager.GetString("ManageAccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Email.
        /// </summary>
        public static string ManageEmail {
            get {
                return ResourceManager.GetString("ManageEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Records.
        /// </summary>
        public static string ManageRecords {
            get {
                return ResourceManager.GetString("ManageRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage existing users.
        /// </summary>
        public static string ManageUsersHeader {
            get {
                return ResourceManager.GetString("ManageUsersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users Page.
        /// </summary>
        public static string ManageUsersTitle {
            get {
                return ResourceManager.GetString("ManageUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value bigger than {1}.
        /// </summary>
        public static string MinValue {
            get {
                return ResourceManager.GetString("MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A code must be supplied for password reset..
        /// </summary>
        public static string MissingPasswordResetCode {
            get {
                return ResourceManager.GetString("MissingPasswordResetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New email.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured..
        /// </summary>
        public static string NoExternalAuthenticationServices {
            get {
                return ResourceManager.GetString("NoExternalAuthenticationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field doesn&apos;t contain a decimal number..
        /// </summary>
        public static string NotADecimalNumber {
            get {
                return ResourceManager.GetString("NotADecimalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be a number..
        /// </summary>
        public static string NotANumber {
            get {
                return ResourceManager.GetString("NotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account contains personal data that you have given us. This page allows you to download or delete that data..
        /// </summary>
        public static string PersonalDataDeclaration {
            get {
                return ResourceManager.GetString("PersonalDataDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        public static string PersonalDataDeletionWarning {
            get {
                return ResourceManager.GetString("PersonalDataDeletionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Data.
        /// </summary>
        public static string PersonalDataTitle {
            get {
                return ResourceManager.GetString("PersonalDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy and cookie policy have not been accepted..
        /// </summary>
        public static string PrivacyAndCookiePolicyNotAccepted {
            get {
                return ResourceManager.GetString("PrivacyAndCookiePolicyNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated.
        /// </summary>
        public static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Record_Categories {
            get {
                return ResourceManager.GetString("Record_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string Record_CreatedOn {
            get {
                return ResourceManager.GetString("Record_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Record_Description {
            get {
                return ResourceManager.GetString("Record_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string Record_Format {
            get {
                return ResourceManager.GetString("Record_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Record_Genres {
            get {
                return ResourceManager.GetString("Record_Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Record_ID {
            get {
                return ResourceManager.GetString("Record_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Record_Photos {
            get {
                return ResourceManager.GetString("Record_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Record_Price {
            get {
                return ResourceManager.GetString("Record_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecordCondition.
        /// </summary>
        public static string Record_RecordCondition {
            get {
                return ResourceManager.GetString("Record_RecordCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Record_Release {
            get {
                return ResourceManager.GetString("Record_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string Record_Styles {
            get {
                return ResourceManager.GetString("Record_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Record_Title {
            get {
                return ResourceManager.GetString("Record_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Record_Year {
            get {
                return ResourceManager.GetString("Record_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Details.
        /// </summary>
        public static string RecordDetails {
            get {
                return ResourceManager.GetString("RecordDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Record Details.
        /// </summary>
        public static string RecordDetailsTitle {
            get {
                return ResourceManager.GetString("RecordDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string RecordsIndexTitle {
            get {
                return ResourceManager.GetString("RecordsIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Title.
        /// </summary>
        public static string RecordTitle {
            get {
                return ResourceManager.GetString("RecordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterAction {
            get {
                return ResourceManager.GetString("RegisterAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string RegisterAsNewUser {
            get {
                return ResourceManager.GetString("RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new user.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register using your {0} account.
        /// </summary>
        public static string RegisterUsing {
            get {
                return ResourceManager.GetString("RegisterUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Lockout.
        /// </summary>
        public static string RemoveLockout {
            get {
                return ResourceManager.GetString("RemoveLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email confirmation.
        /// </summary>
        public static string ResendEmailConfirmation {
            get {
                return ResourceManager.GetString("ResendEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetAction {
            get {
                return ResourceManager.GetString("ResetAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator app.
        /// </summary>
        public static string ResetAuthenticatorApp {
            get {
                return ResourceManager.GetString("ResetAuthenticatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator key.
        /// </summary>
        public static string ResetAuthenticatorKeyAction {
            get {
                return ResourceManager.GetString("ResetAuthenticatorKeyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator key.
        /// </summary>
        public static string ResetAuthenticatorTitle {
            get {
                return ResourceManager.GetString("ResetAuthenticatorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPasswordAction {
            get {
                return ResourceManager.GetString("ResetPasswordAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string ResetPasswordHeader {
            get {
                return ResourceManager.GetString("ResetPasswordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset recovery codes.
        /// </summary>
        public static string ResetRecoveryCodes {
            get {
                return ResourceManager.GetString("ResetRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Română.
        /// </summary>
        public static string ro_RO {
            get {
                return ResourceManager.GetString("ro-RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string ru_RU {
            get {
                return ResourceManager.GetString("ru-RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveAction {
            get {
                return ResourceManager.GetString("SaveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveRecordAction {
            get {
                return ResourceManager.GetString("SaveRecordAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR Code or enter this key {0} into your two factor authenticator app. Spaces and casing do not matter..
        /// </summary>
        public static string ScanQRCode {
            get {
                return ResourceManager.GetString("ScanQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select--.
        /// </summary>
        public static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification email.
        /// </summary>
        public static string SendVerificationEmail {
            get {
                return ResourceManager.GetString("SendVerificationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up authenticator app.
        /// </summary>
        public static string SetupAuthenticatorApp {
            get {
                return ResourceManager.GetString("SetupAuthenticatorApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the policy before you can enable two factor authentication..
        /// </summary>
        public static string ShouldAcceptCookieAndPrivacyFor2FA {
            get {
                return ResourceManager.GetString("ShouldAcceptCookieAndPrivacyFor2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string StringLengthRange {
            get {
                return ResourceManager.GetString("StringLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at max {1} characters long..
        /// </summary>
        public static string StringMaxLength {
            get {
                return ResourceManager.GetString("StringMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        public static string TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("TwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication (2FA).
        /// </summary>
        public static string TwoFactorAuthenticationTitle {
            get {
                return ResourceManager.GetString("TwoFactorAuthenticationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load user with ID {0}..
        /// </summary>
        public static string UnableToLoadUserWithID {
            get {
                return ResourceManager.GetString("UnableToLoadUserWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string UseAnotherServiceToLogIn {
            get {
                return ResourceManager.GetString("UseAnotherServiceToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string UseLocalAccount {
            get {
                return ResourceManager.GetString("UseLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification email sent. Please check your email..
        /// </summary>
        public static string VerificationEmailSent {
            get {
                return ResourceManager.GetString("VerificationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ViewRecordDetailsHeader {
            get {
                return ResourceManager.GetString("ViewRecordDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Details.
        /// </summary>
        public static string ViewRecordDetailsTitle {
            get {
                return ResourceManager.GetString("ViewRecordDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, Admin.
        /// </summary>
        public static string WelcomeAdmin {
            get {
                return ResourceManager.GetString("WelcomeAdmin", resourceCulture);
            }
        }
    }
}
